# Exemplo de implementação de Random Forest
### Referência: 
### https://estatsite.com.br/2020/09/27/random-forest-em-python/


In [10]:
# bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

In [11]:
# Carregando o conjunto de dados 

X, y = datasets.load_wine(as_frame=True, return_X_y = True)



In [16]:
# Dividir os dados em conjunto de treino e teste

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# instanciar o classificador

clf = RandomForestClassifier()

# treinar a base de treino
clf.fit(X_train, y_train)

# aplicar o modelo treinado no teste
y_pred=clf.predict(X_test)

# saídas
print("Acurácia:")
print(accuracy_score(y_test, y_pred))
print("Média:")
print(recall_score(y_test, y_pred, average='macro'))
print("Matriz de Confusão:")
print(confusion_matrix(y_test, y_pred))


Acurácia:
1.0
Média:
1.0
Matriz de Confusão:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
